name=uWire
version=1.0.1
author=AlexGyver <alex@alexgyver.ru>
maintainer=AlexGyver <alex@alexgyver.ru>
sentence=Simple AVR TWI wrapper with Arduino Wire-like API
paragraph=Simple AVR TWI wrapper with Arduino Wire-like API
category=Communication
url=https://github.com/GyverLibs/uWire
architectures=avr